- name: Download JDK rpm
  get_url:
    url: "{{java_download_url}}"
    dest: /tmp/jdk.rpm
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"

- name: Install the downloaded jdk
  yum:
    name: /tmp/jdk.rpm
    state: present
  become: yes